theme: jekyll-theme-minimal 
title: MOKOKO
tagline: "Your tool for tracking all things Lost Ark."
description: "A whole bunch of Lost Ark Resources and Guides that may or may not be helpful."
logo: /assets/favicon.png
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

page_gen-dirs: true # uncomment, if you prefer to generate named folders

page_gen:
  - data: 'outfitters'
    template: 'outfitters'
    name: 'name'
    dir: 'outfits'
